id: PAE804077
initial_creation_type: ocr
source_metadata:
  volumes:
    034eb82535594e439d4f3beaaa4e464b:
      base_file: v012.txt
      image_group_id: I1PD95857
      title: རིན་པོ་ཆེ་རྒྱན་གྱི་སྒྲུབ་པ།
      total_pages: 1544
      volume_number: 12
