id: PAE804077
initial_creation_type: ocr
source_metadata:
  volumes:
    3af425928f004e43b701df0dd2d73188:
      base_file: v012.txt
      image_group_id: I1PD95857
      title: རིན་པོ་ཆེ་རྒྱན་གྱི་སྒྲུབ་པ།
      total_pages: 1544
      volume_number: 12
