id: D9F39EA4F
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-01-05T06:53:26+00:00'
last_modified: '2022-05-26T08:01:59.449467+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    '2901':
      image_group_id: I1PD95857
      title: རིན་པོ་ཆེ་རྒྱན་གྱི་སྒྲུབ་པ།
      total_pages: 1544
      order: 12
      base_file: 2901.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
